Rename CRYPT_MAP --> LUKS_NAME and CRYPT_NAME --> CRYPT_FNAME
also changed LUKS_NAME to "liveb"

diff --git a/init b/init
--- a/init
+++ b/init
@@ -86,8 +86,8 @@
 
           VID_NAME=VID
       LINUXFS_NAME=linuxfs
-        CRYPT_NAME=crypt
-         CRYPT_MAP=live
+       CRYPT_FNAME=crypt
+         LUKS_NAME=liveb
       PHRASE_FNAME=.passphrase
 
         BLACK_LIST=
@@ -378,7 +378,7 @@ main_core() {
     # will always work
     #[ "$NO_EHCI" ] && disable_hcd ehci
 
-    #[ "$SET_CRYPT" -a -z "$NO_CRYPT" ] && setup_crypt "$CRYPT_ID" "$BOOT_DIR/$CRYPT_NAME" "$BOOT_MP"
+    #[ "$SET_CRYPT" -a -z "$NO_CRYPT" ] && setup_crypt "$CRYPT_ID" "$BOOT_DIR/$CRYPT_FNAME" "$BOOT_MP"
 
     breakpoint 3 "before looking for linuxfs file"
 
@@ -668,7 +668,7 @@ read_cmdline_params()
                      passphrase) CHANGE_PASSPHRASE=true                          ;;
                         nocrypt) NO_CRYPT=true                                   ;;
 #-?                          crypt)                             SET_CRYPT=true      ;;
-#-?                        crypt=*) CRYPT_NAME=$value        ;  SET_CRYPT=true      ;;
+#-?                        crypt=*) CRYPT_FNAME=$value        ;  SET_CRYPT=true      ;;
 #-?   cryptlabel=*|clabel=*|clab=*) CRYPT_ID=label=$value    ;  SET_CRYPT=true      ;;
 #-?            cryptuuid=*|cuuid=*) CRYPT_ID=uuid=$value     ;  SET_CRYPT=true      ;;
 #-?              cryptdev=*|cdev=*) CRYPT_ID=dev=$value      ;  SET_CRYPT=true      ;;
@@ -2052,7 +2052,7 @@ find_linuxfs_file() {
         else
             # Look for crypt file as well as sqfile_file
             local boot_dir=$(dirname $SQFILE_FILE)
-            local crypt_full="$boot_dir/$CRYPT_NAME"
+            local crypt_full="$boot_dir/$CRYPT_FNAME"
             local files="$crypt_full $SQFILE_FILE"
             msg "Look for files %s" "<$(fq $files)>"
 
@@ -2094,8 +2094,8 @@ find_linuxfs_file() {
                 fi
 
                 warn "Found encrypted device.  You will be asked to enter your passphrase below."
-                cttyhack cryptsetup open --type luks $crypt_dev $CRYPT_MAP || fatal "Could not open LUKS device %s" $crypt_dev
-                local mapper_dev=/dev/mapper/$CRYPT_MAP
+                cttyhack cryptsetup open --type luks $crypt_dev $LUKS_NAME || fatal "Could not open LUKS device %s" $crypt_dev
+                local mapper_dev=/dev/mapper/$LUKS_NAME
                 msg "Opened encrypted device %s at %s" "$crypt_dev" "$mapper_dev"
                 try_mount "$mapper_dev" "$BOOT_MP" || fatal "Could not mount encrypted device"
                 test -e "$BOOT_MP/$SQFILE_FILE" || fatal "Could not find file %s on encrypted partition" "$SQFILE_FILE"
@@ -5191,7 +5191,7 @@ late_umount() {
 
     # If this was the encrypted device then close the mapping
     [ "$dev" = "$CRYPT_DEV" ] || return
-    log_cmd chroot /live/aufs /sbin/cryptsetup close "$CRYPT_MAP"
+    log_cmd chroot /live/aufs /sbin/cryptsetup close "$LUKS_NAME"
 }
 
 write_ntfs_pids() {
