Improve module loading: faster, add load= option

diff --git a/init b/init
--- a/init
+++ b/init
@@ -72,7 +72,7 @@
           VID_NAME=VID
       LINUXFS_NAME=linuxfs
 
-           NO_LOAD=
+      NO_LOAD_LIST=
            DO_LOAD=
       DISABLE_LOAD=
 
@@ -249,7 +249,7 @@ main_core() {
     show_integer_errors "$INTEGER_ERRORS"
 
     breakpoint 2 "before loading modules"
-    load_kernel_modules "$NO_LOAD" "$DO_LOAD"
+    load_kernel_modules "$NO_LOAD_LIST" "$DO_LOAD" "$MODULE_LIST"
 
     : ${SQFILE_FILE:=$DEFAULT_SQFILE}
     : ${SQFILE_NAME:=${SQFILE_FILE##*/}}
@@ -500,11 +500,11 @@ read_cmdline_params()
                         checkfs) FORCE_FSCK=true                                 ;;
                       nocheckfs) DO_FSCK=                                        ;;
 
-#                         load=*) MODULE_LIST=$MODULE_LIST,$value                 ;;
+                         load=*) MODULE_LIST=$MODULE_LIST,$value                 ;;
 #                           load) DO_LOAD=true                                    ;;
 #                         noload) DO_LOAD=                                        ;;
                           noload) DISABLE_LOAD=true                              ;;
-                        noload=*) NO_LOAD=$NO_LOAD,$value                        ;;
+                        noload=*) NO_LOAD_LIST=$NO_LOAD_LIST,$value              ;;
 
                       nohotplug) DO_HOTPLUG=                                     ;;
                       traceload) TRACE_LOAD=true                                 ;;
@@ -867,12 +867,13 @@ disable_hcd() {
 }
 
 load_kernel_modules() {
-    local no_load=$1 do_load=$2  file=$CUSTOM_DIR/$DISTRO_NAME/modules.load
+    local no_load=$1 do_load=$2  list=$3 file=$CUSTOM_DIR/$DISTRO_NAME/modules.load
 
     if [ "$no_load" ]; then
         no_load=$(echo $no_load | sed 's/VIDEO/nouveau,nvidia,i915,radeon/');
         mkdir -p /etc/modprobe.d/
         echo $no_load | sed 's/,/\n/g' | sed -r 's/^([a-z])/blacklist \1/' >> /etc/modprobe.d/initrd.conf
+        BLACKLIST_OPT=-b
     fi
 
     [ "$DISABLE_LOAD" ] && return
@@ -881,44 +882,55 @@ load_kernel_modules() {
     depmod &>/dev/null
 
     # These ones must be loaded before the others
-    local mod
-    for mod in $LOAD_FIRST; do
-        modprobe -q -b $mod 2>/dev/null
+    local module
+    for module in $LOAD_FIRST; do
+        modprobe -q $BLACKLIST_OPT $module 2>/dev/null
     done
 
     if [ -r $file -a -n "$do_load" ]; then
         vmsg 7 'Load modules from file %s' "$(fq $file)"
-        for module in $(grep -v "^\s*#" $file | sed 's/\s*#.*//' ); do
-            modprobe -q -b $module
-        done
+        grep -v "^\s*#" $file | sed 's/\s*#.*//' | xargs modprobe -a -q $BLACKLIST_OPT
     fi
+
     autoload_modules 5
+
+    for module in $(echo $list | sed 's/,/ /g'); do
+        case $module in
+            all) load_all_modules live/ ;;
+            ALL) load_all_modules       ;;
+              *) modprobe -q $module || warn  "Could not load module %s" $(pqw $module);;
+        esac
+    done
+
 }
 
 load_all_modules() {
-
+    local subdir=$1
     msg "Loading all live modules"
-    local list=$(find $MOD_DIR/live -name "*.ko" | sed -e 's=.*/==' -e 's/\.ko$//')
-    local module
-    for module in $list; do
-        modprobe -q -b $module
-    done
+    find $MOD_DIR/$subdir -name "*.ko" | sed -e 's=.*/==' -e 's/\.ko$//' \
+        | xargs modprobe -q $BLACKLIST_OPT
 }
 
 autoload_modules() {
-    local alias  module  count  verb=$1
-    local log_file=/live/config/auto-load.log
+    local verb=$1
 
     [ "$DISABLE_LOAD" ] && return
 
     [ "$verb" ] && vmsg $verb "Loading hardware specific modules ..."
 
-    local alias_file alias
-    find /sys/devices -name modalias | while read alias_file; do
-        alias=$(cat $alias_file 2>/dev/null)
-        modprobe -q -b $alias 2>/dev/null
-        echo $alias >> $log_file
-    done
+    #find /sys/devices -name uevent -exec grep -h ^MODALIAS= '{}' + 2>/dev/null | sort -u \
+    #    | cut -c 10- | xargs modprobe -a -q $BLACKLIST_OPT
+    #return
+
+    find /sys/devices -name modalias -exec cat '{}' + | sort -u \
+         | xargs modprobe -a -q $BLACKLIST_OPT 2>/dev/null
+    return
+
+    # local alias_file alias
+    # find /sys/devices -name modalias | while read alias_file; do
+    #     alias=$(cat $alias_file 2>/dev/null)
+    #     modprobe -q $BLACKLIST_OPT $alias 2>/dev/null
+    # done
 }
 
 #==============================================================================
