Reorganize the code.  Utilities toward the bottom, etc

diff --git a/etc/init.d/live-hwclock b/etc/init.d/live-hwclock
--- a/etc/init.d/live-hwclock
+++ b/etc/init.d/live-hwclock
@@ -86,8 +86,41 @@ ask_hwclock() {
     check_hwclock
 }
 
-check_hwclock() {
+check_timezone() {
+    test -r $TZ_FILE || fatal "Could not find file %s" $(pquote $TZ_FILE)
+    local orig_tz
+    read orig_tz 2>/dev/null <$TZ_FILE
+    : ${TZ:=$orig_tz}
+    [ ${#TZ} -eq 0 ] && fatal "No timezone found in file %s" $(pquote $TZ_FILE)
 
+    while true ; do
+        yes_no_quit "$LIVE_COLOR$(printf "Is %s your current timezone" "$(pquote $TZ)")"
+        local ret=$?
+        case $ret in
+             0) if [ "$orig_tz" != "$TZ" ]; then
+                    echo $TZ > $TZ_FILE
+                    export TZ
+                fi
+                return 0     ;;
+             1) set_timezone ;;
+             2) return 1     ;;
+        esac
+    done
+}
+
+set_timezone() {
+    local DISTRO distro_file=/live/config/distro
+    test -r distro_file && read DISTRO 2>/dev/null $distro_file
+    : ${DISTRO:=MX}
+
+    local BOOT_MENU_DIR=/live/custom/$DISTRO/menus DO_MENUS=t
+    my_select_menu "Select Timezone" "Timezones are listed geographically" t timezone
+    local tz=${timezone#tz=}
+    [ "$tz" = "default" ] && tz=$TZ
+    TZ=$tz
+}
+
+check_hwclock() {
     # Get current default locale
     local locale_file=/etc/default/locale
     test -r $locale_file && . $locale_file
@@ -127,13 +160,6 @@ check_hwclock() {
     else
         guess_hwclock "$utc_str" "$loc_str"
     fi
-
-    # case $found_utc:$found_loc in
-    #         true:) do_found utc   ;;
-    #         :true) do_found local ;;
-    #     true:true) FIXME          ;;
-    #             :) do_neither     ;;
-    # esac
 }
 
 guess_hwclock() {
@@ -168,98 +194,6 @@ Select_Menu
           neither) do_neither          ;;
              both) do_both             ;;
                 *) error "Got a strange answer from guess hwclock menu %s" "$answer" ;;
-    esac
-}
-
-show_time() { echo_live "%12s:$START_PARAM %s" "$1" "$2"; }
-show_unix() { echo_live "%15s Unix:$START_PARAM %10s" "$1" "$2" ; }
-
-get_hwclock() { LANG=en_US.UTF-8 hwclock --show $* | sed 's/  .*//'; }
-
-check_timezone() {
-    test -r $TZ_FILE || fatal "Could not find file %s" $(pquote $TZ_FILE)
-    local orig_tz
-    read orig_tz 2>/dev/null <$TZ_FILE
-    : ${TZ:=$orig_tz}
-    [ ${#TZ} -eq 0 ] && fatal "No timezone found in file %s" $(pquote $TZ_FILE)
-
-    while true ; do
-        yes_no_quit "$LIVE_COLOR$(printf "Is %s your current timezone" "$(pquote $TZ)")"
-        local ret=$?
-        case $ret in
-             0) if [ "$orig_tz" != "$TZ" ]; then
-                    echo $TZ > $TZ_FILE
-                    export TZ
-                fi
-                return 0     ;;
-             1) set_timezone ;;
-             2) return 1     ;;
-        esac
-    done
-}
-
-set_timezone() {
-    local DISTRO distro_file=/live/config/distro
-    test -r distro_file && read DISTRO 2>/dev/null $distro_file
-    : ${DISTRO:=MX}
-
-    local BOOT_MENU_DIR=/live/custom/$DISTRO/menus DO_MENUS=t
-    my_select_menu "Select Timezone" "Timezones are listed geographically" t timezone
-    local tz=${timezone#tz=}
-    [ "$tz" = "default" ] && tz=$TZ
-    TZ=$tz
-}
-
-show_all() {
-    echo_live
-    show_time utc_en          "$utc_en"
-    show_time local_en        "$loc_en"
-    show_time utc             "$utc_str"
-    show_time local           "$loc_str"
-    show_time "tz offset"     "$tz_offset"
-    echo_live
-    show_unix system          "$sys_unix"
-    show_unix utc             "$utc_unix"
-    show_unix "|sys - utc|"   "$diff_sys_utc"
-    show_unix "local"         "$loc_unix"
-    show_unix "|sys - local|" "$diff_sys_loc"
-    show_unix "|utc - local|" "$diff_utc_loc"
-}
-
-yes_no_quit() {
-    local ans title=$1
-    local fmt="  $GREEN%2s$WHITE) $CYAN%s$NO_COLOR\n"
-
-    while true; do
-        echo -e "$title?"
-        printf "$fmt" 1 "yes"
-        printf "$fmt" 2 "no"
-        printf "$fmt" 3 "quit"
-        printf "$GREEN%s \"%s\" >$NO_COLOR " "Please enter a number.  Default is" "yes"
-
-        read ans
-        case $ans in
-                 ""|1) return 0           ;;
-                    2) return 1           ;;
-                    3) ask_really_quit    ;;
-        esac
-        if [ $ans -ne 3 ]; then
-            error "$(printf "%s $ERROR_PARAM_COLOR%s" "You must enter 0, 1, or 2." "Press <enter>")"
-            read ans
-        fi
-    done
-}
-
-ask_really_quit() {
-    local ans fmt="  $GREEN%2s$WHITE) $CYAN%s$NO_COLOR\n"
-    printf "\n$GREEN%s\n"  "Really quit?"
-    printf "$fmt" 1 "yes"
-    printf "$fmt" 2 "no"
-    printf "$GREEN%s \"%s\" >$NO_COLOR " "Please enter a number.  Default is" "no"
-    read ans
-    case $ans in
-        1) exit 0 ;;
-        *) return ;;
     esac
 }
 
@@ -299,6 +233,43 @@ Manual_Data
     case $answer in
         utc|local) set_hwclock $answer ;;
                 *) exit 0              ;;
+    esac
+}
+
+yes_no_quit() {
+    local ans title=$1
+    local fmt="  $GREEN%2s$WHITE) $CYAN%s$NO_COLOR\n"
+
+    while true; do
+        echo -e "$title?"
+        printf "$fmt" 1 "yes"
+        printf "$fmt" 2 "no"
+        printf "$fmt" 3 "quit"
+        printf "$GREEN%s \"%s\" >$NO_COLOR " "Please enter a number.  Default is" "yes"
+
+        read ans
+        case $ans in
+                 ""|1) return 0           ;;
+                    2) return 1           ;;
+                    3) ask_really_quit    ;;
+        esac
+        if [ $ans -ne 3 ]; then
+            error "$(printf "%s $ERROR_PARAM_COLOR%s" "You must enter 0, 1, or 2." "Press <enter>")"
+            read ans
+        fi
+    done
+}
+
+ask_really_quit() {
+    local ans fmt="  $GREEN%2s$WHITE) $CYAN%s$NO_COLOR\n"
+    printf "\n$GREEN%s\n"  "Really quit?"
+    printf "$fmt" 1 "yes"
+    printf "$fmt" 2 "no"
+    printf "$GREEN%s \"%s\" >$NO_COLOR " "Please enter a number.  Default is" "no"
+    read ans
+    case $ans in
+        1) exit 0 ;;
+        *) return ;;
     esac
 }
 
@@ -368,14 +339,33 @@ abs_diff() {
     echo ${diff#-}
 }
 
+show_all() {
+    echo_live
+    show_time utc_en          "$utc_en"
+    show_time local_en        "$loc_en"
+    show_time utc             "$utc_str"
+    show_time local           "$loc_str"
+    show_time "tz offset"     "$tz_offset"
+    echo_live
+    show_unix system          "$sys_unix"
+    show_unix utc             "$utc_unix"
+    show_unix "|sys - utc|"   "$diff_sys_utc"
+    show_unix "local"         "$loc_unix"
+    show_unix "|sys - local|" "$diff_sys_loc"
+    show_unix "|utc - local|" "$diff_utc_loc"
+}
+
 bold()   { echo "$bold_co$*$nc_co"        ;}
 pqe()    { echo "$bold_co$*$err_co"       ;}
 cq()     { echo "$cheat_co$*$m_co"        ;}
 pqe()    { echo "$bold_co$*$err_co"       ;}
 
-debug() {
-    [ ${#db_hwc} -gt 0 ] && echo "$*"
-}
+get_hwclock() { LANG=en_US.UTF-8 hwclock --show $* | sed 's/  .*//'; }
+
+show_time() { echo_live "%12s:$START_PARAM %s" "$1" "$2"; }
+show_unix() { echo_live "%15s Unix:$START_PARAM %10s" "$1" "$2" ; }
+
+debug() { [ ${#db_hwc} -gt 0 ] && echo "$*"; }
 
 #-------------------------------------------------------------------------------
 #-------------------------------------------------------------------------------
